<?$APPLICATION->IncludeComponent("bitrix:catalog.products.viewed", "", 
	array(
		"IBLOCK_MODE" => "single",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "#ITEMS_IBLOCK_ID#",
		"SHOW_FROM_SECTION" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PAGE_ELEMENT_COUNT" => "15",
		"PRICE_CODE" => array(),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "#SITE_DIR#personal/cart/",
		"USE_PRODUCT_QUANTITY" => "N",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"DISPLAY_COMPARE" => "N",
		"PROPERTY_CODE_#ITEMS_IBLOCK_ID#" => array(),
		"CART_PROPERTIES_#ITEMS_IBLOCK_ID#" => array(),
		"ADDITIONAL_PICT_PROP_#ITEMS_IBLOCK_ID#" => "-",
		"LABEL_PROP_#ITEMS_IBLOCK_ID#" => array(),
		"PROPERTY_CODE_#OFFERS_IBLOCK_ID#" => array(),
		"CART_PROPERTIES_#OFFERS_IBLOCK_ID#" => array(),
		"ADDITIONAL_PICT_PROP_#OFFERS_IBLOCK_ID#" => "-",
		"OFFER_TREE_PROPS_#OFFERS_IBLOCK_ID#" => array()
	),
	false
);?>